# Generated by Django 5.2.12 on 2026-04-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date',
            new_name='appointment_time',
        ),
    ]
