# Generated by Django 5.2.12 on 2026-04-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_rename_doctors_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specification',
            new_name='specialization',
        ),
    ]
